nikki/urls.py
from django.urls import path
from . import views

app_name = 'nikki'

urlpatterns = [
    path('', views.ArticleList.as_view(), name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('search/', views.SearchList.as_view(), name='search'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('rules/', views.RulesView.as_view(), name='rules'),
    path('privacy/', views.PrivacyView.as_view(), name='privacy'),
    # User
    path('create_user/', views.CreateUser.as_view(), name='create_user'),
    path('create_user/done', views.CreateUserDone.as_view(), name='create_user_done'),
    path('create_user/complete/<uidb64>/<token>/', views.CreateUserComplete.as_view(), name='create_user_complete'),
    path('user_detail/<int:pk>/', views.DetailUser.as_view(), name='detail_user'),
    path('user_update/<int:pk>/', views.UpdateUser.as_view(), name='update_user'),
    path('user_delete/<int:pk>/', views.DeleteUser.as_view(), name='delete_user'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    # Article
    path('create_article/<int:user_id>', views.create_article, name='create_article'),
    path('detail_article/<int:pk>', views.DetailArticle.as_view(), name='detail_article'),
    path('update_article/<int:pk>', views.update_article, name='update_article'),
    path('delete_article/<int:pk>', views.DeleteArticle.as_view(), name='delete_article'),
    path('author_articles/<int:user_id>', views.AuthorArticles.as_view(), name='author_articles'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category'),
    # Comment
    path('comment/<int:article_id>', views.create_comment, name='comment'),
    path('detail_comment/<int:pk>', views.DetailComment.as_view(), name='detail_comment'),
    path('update_comment/<int:pk>', views.UpdateComment.as_view(), name='update_comment'),
    path('delete_comment/<int:pk>', views.DeleteComment.as_view(), name='delete_comment'),

]

nikki_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nikki.urls')),
]

nikki/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm, PasswordChangeForm,
    PasswordResetForm, SetPasswordForm
)
from django.contrib.auth import get_user_model
from .models import Article, Comment, Category, User

from django.core.mail import send_mail
from django.conf import settings

import logging
User = get_user_model()


def info(msg):
    logger = logging.getLogger('command')
    logger.info(msg)


class LoginForm(AuthenticationForm):
    """
    ログインフォーム
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる


class CreateUserForm(UserCreationForm):
    """
    ユーザー登録用フォーム
    """
    class Meta:
        model = User
        fields = ('email', 'nickname', 'agegroup')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    agegroup = forms.ChoiceField(label='年代', choices=User.AGEGROUPS)


class UpdateUserForm(forms.ModelForm):
    """
    ユーザー情報更新フォーム
    """
    class Meta:
        model = User
        fields = ('email', 'nickname', 'agegroup',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    agegroup = forms.ChoiceField(label='年代' ,choices=User.AGEGROUPS)


class MyPasswordChangeForm(PasswordChangeForm):
    """
    パスワード変更フォーム
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MyPasswordResetForm(PasswordResetForm):
    """
    パスワード忘れたときのフォーム
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(SetPasswordForm):
    """
    パスワード再設定用フォーム(パスワード忘れて再設定)
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class ArticleForm(forms.ModelForm):
    """
    Article投稿フォーム
    """
    class Meta:
        model = Article
        fields = ('category_id', 'title', 'text', 'failure_image')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    # CATEGORYS = ((e.id, e.name) for e in Category.objects.all())
    CATEGORIES = ((1, '日常'), (2, '仕事'), (3, '学校'), (4, '恋愛'), (5, '勉強'), (6, 'その他'))

    category_id = forms.ChoiceField(label='カテゴリ', choices=CATEGORIES)
    title = forms.CharField(label='タイトル', max_length=100, widget=forms.TextInput(
            attrs={'placeholder':'タイトル',}))
    text = forms.CharField(label='本文', widget=forms.Textarea(
            attrs={'placeholder':'本文', 'class':'article_text'}), max_length=2500)
    failure_image = forms.ChoiceField(label='画像選択', choices=Article.IMAGES)


class CommentForm(forms.ModelForm):
    """
    コメント投稿フォーム
    """
    class Meta:
        model = Comment
        fields = ('text',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class ContactForm(forms.Form):
    """
    問い合わせフォーム
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    name = forms.CharField(label='お名前', required=True,)
    email = forms.EmailField(label='メールアドレス', required=True,)
    message = forms.CharField(label='お問い合わせ内容', widget=forms.Textarea,  required=True)

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        subject = self.cleaned_data['name']
        message = self.cleaned_data['message']
        from_email = self.cleaned_data['email']
        to = [settings.EMAIL_HOST_USER]

        send_mail(subject, message, from_email, to)

nikki/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.views import generic
from .forms import (
    LoginForm, CreateUserForm, UpdateUserForm, MyPasswordChangeForm,
    MyPasswordResetForm, MySetPasswordForm, ArticleForm, CommentForm
)
from .models import Article, Category, Comment
from django.db.models import Q

from django.contrib import messages
from django.contrib.auth import get_user_model, login
from django.contrib.sites.shortcuts import get_current_site
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import redirect, resolve_url
from django.template.loader import get_template
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.urls import reverse_lazy

from django.views.generic.edit import FormView
from .forms import ContactForm


User = get_user_model()


class Login(LoginView):
    """
    ログインページ
    """
    form_class = LoginForm
    template_name = 'nikki/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    """
    ログアウトページ
    """
    template_name = 'nikki/article_list.html'


class CreateUser(generic.CreateView):
    """
    ユーザー仮登録
    """
    template_name = 'nikki/user_create.html'
    form_class = CreateUserForm

    def form_valid(self, form):
        """
        仮登録と本登録用メールの発行
        """
        # 仮登録と本登録の切り替えは、is_active属性を使う。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'uidb64': urlsafe_base64_encode(force_bytes(user.pk)).decode('utf-8'),
            'token': urlsafe_base64_encode(force_bytes(user.email)).decode('utf-8'),
            'user': user,
        }

        # テンプレートを使ってメールを組み立てる
        subject_template = get_template('nikki/mail_templates/create/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('nikki/mail_templates/create/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)  # ユーザーのメール送信メソッド
        return redirect('nikki:create_user_done')


class CreateUserDone(generic.TemplateView):
    """
    ユーザー仮登録完了
    """
    template_name = 'nikki/user_create_done.html'


class CreateUserComplete(generic.TemplateView):
    """
    メール内URLアクセス後のユーザー本登録
    """
    template_name = 'nikki/user_create_complete.html'

    def get(self, request, **kwargs):
        """
        uid、tokenが正しければ本登録
        """
        token = kwargs.get('token')
        uidb64 = kwargs.get('uidb64')
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            email = force_text(urlsafe_base64_decode(token))
            user = User.objects.get(pk=uid, email=email)
            if user.is_active:    # すでにis_activeがTrueなら、処理は必要ないので404
                raise Http404
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            pass
        else:
            user.is_active = True
            user.save()
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            login(request, user)

            return super().get(request, **kwargs)

        raise Http404


class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class DetailUser(OnlyYouMixin, generic.DetailView):
    model = User
    template_name = 'nikki/user_detail.html'

    def get_context_data(self, **kwargs):
        user_id = self.kwargs['pk']
        author = get_object_or_404(User, pk=user_id)
        context = super().get_context_data(**kwargs)
        context['articles_list'] = Article.objects.filter(user=author).order_by('-created_at')
        return context


class UpdateUser(OnlyYouMixin, generic.UpdateView):
    model = User
    form_class = UpdateUserForm
    template_name = 'nikki/user_form.html'

    def get_success_url(self):
        return resolve_url('nikki:detail_user', pk=self.kwargs['pk'])

    def form_valid(self, form):
        messages.success(self.request, "内容を更新しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "内容を更新できませんでした")
        return super().form_invalid(form)



class DeleteUser(OnlyYouMixin, generic.DeleteView):
    model = User
    success_url = reverse_lazy("nikki:index")

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "アカウント及び記事を削除しました")
        return super().delete(request, *args, **kwargs)



class PasswordChange(PasswordChangeView):
    """
    パスワード変更ビュー
    """
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('nikki:password_change_done')
    template_name = 'nikki/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    template_name = 'nikki/password_change_done.html'


class PasswordReset(PasswordResetView):
    """
    パスワード変更用URLの送付ページ
    """
    subject_template_name = 'nikki/mail_templates/reset/subject.txt'
    email_template_name = 'nikki/mail_templates/reset/message.txt'
    template_name = 'nikki/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('nikki:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """
    パスワード変更用URLを送りましたページ
    """
    template_name = 'nikki/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """
    新パスワード入力ページ
    """
    form_class = MySetPasswordForm
    success_url = reverse_lazy('nikki:password_reset_complete')
    template_name = 'nikki/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """
    新パスワード設定しましたページ
    """
    template_name = 'nikki/password_reset_complete.html'


class AboutView(generic.TemplateView):
    template_name = 'nikki/about.html'


class SearchList(generic.ListView):
    model = Article
    template_name = 'nikki/search_list.html'
    paginate_by = 12

    def get_queryset(self):
        queryset = Article.objects.order_by('-created_at')
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(
            Q(title__icontains=keyword) | Q(text__icontains=keyword)
            )
        return queryset


class ArticleList(generic.ListView):
    model = Article
    template_name = 'nikki/article_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_life'] = Article.objects.filter(category=1).order_by('-created_at')[:3]
        context['category_work'] = Article.objects.filter(category=2).order_by('-created_at')[:3]
        context['category_school'] = Article.objects.filter(category=3).order_by('-created_at')[:3]
        context['category_love'] = Article.objects.filter(category=4).order_by('-created_at')[:3]
        context['category_study'] = Article.objects.filter(category=5).order_by('-created_at')[:3]
        context['category_triviality'] = Article.objects.filter(category=6).order_by('-created_at')[:3]
        return context


def create_article(request, user_id):
    """
    日記投稿ページ
    """
    model = Article
    template_name = 'nikki/article_form.html'
    user = get_object_or_404(User, pk=user_id)
    posted_article_title = request.POST.get('title')
    posted_article_text = request.POST.get('text')
    posted_user_id = request.POST.get('user_id')
    posted_category_id = request.POST.get('category_id')
    posted_failure_image = request.POST.get('failure_image')

    form = ArticleForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            p = Article(title=posted_article_title, text=posted_article_text, user_id=user_id, category_id=posted_category_id, failure_image=posted_failure_image)
            p.save()
            messages.success(request, '日記を投稿しました')
            return redirect('nikki:detail_user', pk=user_id)
        else:
            messages.error(request, "日記の投稿に失敗しました")
            return redirect('nikki:detail_user', pk=user_id)

    context = {
    'form':form
    }
    return render(request, 'nikki/article_form.html', context)


class DetailArticle(generic.DetailView):
    model = Article

    def get_context_data(self, **kwargs):
        article_pk = self.kwargs['pk']
        article = get_object_or_404(Article, pk=article_pk)
        author = User.objects.get(article=article_pk)
        context = super().get_context_data(**kwargs)
        context['user_article'] = Article.objects.filter(user=author).order_by('-created_at')[:5]
        return context


def update_article(request, pk):
    """
    日記更新ページ
    """
    template_name = 'nikki/article_form.html'
    article = get_object_or_404(Article, pk=pk)
    form = ArticleForm(request.POST or None, instance=article,  initial = {
    'category_id': article.category_id})

    if request.method == 'POST':
        if form.is_valid():
            posted_category_id = request.POST.get('category_id')
            article.category_id = Category.objects.get(pk = posted_category_id)
            article.category_id.save()
            messages.success(request, '記事を更新しました')
            form.save()
            return redirect('nikki:detail_article', pk=pk)
        else:
            messages.error(request, "記事の更新に失敗しました")

nikki/templates/nikki/base.html
{% load static %}
<!doctype html>
<html lang="ja">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">

  <!-- meta tag - title, keywords, description, author -->
  <meta name="keywords" content="失敗,日記,ニックネーム">
  <meta name="description" content="失敗を投稿してみませんか？">
  <meta name="author" content="Takaaki Uno">

  <meta name="apple-mobile-web-app-title" content="失敗diary">

  <!-- favicon -->
  <link rel="icon" type="image/x-icon" href="{% static 'nikki/favicons/favicon.ico' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'nikki/favicons/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'nikki/favicons/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'nikki/favicons/favicon-16x16.png' %}">
  <link rel="icon" type="image/png" sizes="192x192" href="{% static 'nikki/favicons/android-chrome-192×192.png' %}">
  <link rel="icon" type="image/png" sizes="512x512" href="{% static 'nikki/favicons/android-chrome-512×512.png' %}">
  <link rel="manifest" href="{% static 'nikki/favicons/site.webmanifest' %}">
  <link rel="mask-icon" href="{% static 'nikki/favicons/safari-pinned-tab.svg' %}" color="#5bbad5">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">

  <!-- twitter card -->

  <!-- facebook ogp -->

  <!-- Let browser know website is optimized for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

  <!-- fontawesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-123015359-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-123015359-1');
  </script>

  <!-- css -->
  <link rel="stylesheet" href="{% static 'nikki/common.css' %}" />
  {% block extracss %}{% endblock %}

  <title>{% block title %}{% endblock %}</title>

</head>

<body>
  <!-- header -->
  <header>
    <nav class="navbar navbar-expand-md navbar-light">
      <a class="navbar-brand font-weight-bold text-white" href="{% url 'nikki:index' %}">
        失敗diary
      </a>
      <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'nikki:about' %}">
              サイトについて <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link font-weight-bold text-white" href="{% url 'nikki:logout' %}">
              ログアウト
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link font-weight-bold text-white"  href="{% url 'nikki:detail_user' user.pk %}">
              {{ user.nickname|truncatechars:12 }}
            </a>
          </li>
            {% else %}
            <a class="nav-link font-weight-bold text-white" href="{% url 'nikki:login' %}">
              新規登録/ログイン
            </a>
            {% endif %}
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'nikki:search' %}">
          <input class="form-control mr-sm-2" type="text" placeholder="日記を検索" aria-label="Search" name="keyword">
          <button class="btn btn-outline-light my-2 my-sm-0" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </form>
      </div>
    </nav>
  </header>

  <main>
    {% if messages %}
    <ul class="list-unstyled">
      {% for message in messages %}
      <li{% if message.tags %}
        class=" font-weight-bold alert alert-{% if message.tags == 'error' %}danger{% else %}success{% endif %}"{% endif %}>
        {{ message }}
        <button type="button" class="close" aria-label="Close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </li>
      {% endfor %}
    </ul>
    {% endif %}

    {% block content %}
    {% endblock %}
  </main>

  <footer class="py-4 px-5 " id="foot">
    <div class="container">
      <div class="footer_link row text-center">
        <div class="col-12 col-md-6">
          <ul class="list-unstyled">
            <li>
              <a  class="text-secondary d-inline-block" href="{% url 'nikki:about' %}">
                失敗diaryとは
              </a>
            </li>
          </ul>
        </div>

        {% if user.is_authenticated %}
        <div class="col-12 col-md-6">
          <ul class="list-unstyled">
            <li>
              <a class="text-secondary" href="{% url 'nikki:detail_user' user.pk %}">
                アカウント情報
              </a>
            </li>
          </ul>
        </div>
        {% endif %}

        <div class="col-12 col-md-6">
          <ul class="list-unstyled">
            {% if user.is_authenticated %}
            <li>
              <a class="text-secondary" href="{% url 'nikki:logout' %}">
                ログアウト
              </a>
            </li>
            {% else %}
            <li>
              <a class="text-secondary" href="{% url 'nikki:login' %}">
                新規登録/ログイン
              </a>
            </li>
            {% endif %}
          </ul>
        </div>

        <div class="col-12 col-md-6">
          <ul class="list-unstyled">
            <li>
              {% if user.is_authenticated %}
              <a class="text-secondary" href="{% url 'nikki:create_article' user.pk %}">
                日記を書く
              </a>
              {% else %}
              <a class="text-secondary" href="{% url 'nikki:login' %}">
                日記を書く
              </a>
              {% endif %}
            </li>
          </ul>
        </div>

        <div class="col-12 col-md-6">
          <ul class="list-unstyled">
            <li>
              <a class="text-secondary" href="{% url 'nikki:rules' %}">
                利用規約
              </a>
            </li>
          </ul>
        </div>

        <div class="col-12 col-md-6">
          <ul class="list-unstyled">
            <li>
              <a class="text-secondary" href="{% url 'nikki:privacy' %}">
                プライバシーポリシー
              </a>
            </li>
          </ul>
        </div>

        <div class="col-12 col-md-6">
          <ul class="list-unstyled">
            <li>
              <a class="text-secondary" href="{% url 'nikki:contact' %}">
                お問い合わせ
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</body>

</html>

nikki/templates/nikki/comment_confirm_delete.html
{% extends "nikki/base.html" %}

{% block title %}コメントの削除確認{% endblock %}

{% block content %}
<div class="container">
  <div class="col-12 text-center">
    <h1>削除の確認</h1>
    <p class="text-danger">以下のコメントを本当に削除しますか？</p>
    <p class="title mb-0 py-3">{{ comment.text }}</p>

    <form method="post">
    {% csrf_token %}
     {{ form }}

     <a href="{% url 'nikki:detail_comment' comment.id %}" class="mr-4">キャンセル</a>
     <button type="submit" class="switch-2 btn text-white">削除する</button>

   </form>

  </div>
</div>


{% endblock %}

nikki/templates/nikki/user_detail.html
{% extends "nikki/base.html" %}

{% block title %}{{ user.nickname }}{% endblock %}

{% block content %}
<div class="container">
  <div class="mx-3 mb-5">
    <p class="border-top text-secondary font-weight-bold mb-0 pt-3">ニックネーム</p>
    <p class="text">{{ user.nickname }}</p>
    <p class="border-top text-secondary font-weight-bold mb-0 pt-3">年代</p>
    <p>{{ user.agegroup }}</p>
    <p class="border-top text-secondary font-weight-bold mb-0 pt-3">メールアドレス</p>
    <p class="text">{{ user.email }}</p>
  </div>

  <div class="row my-5 my-md-4 text-center mx-auto">
    <div class="col-12 col-md-4 mb-4">
      <a class="d-inline-block text-secondary font-weight-normal" href="{% url 'nikki:update_user' user.pk %}">
        アカウント情報の編集
      </a>
    </div>

    <div class="col-12 col-md-4 mb-4">
      <a class="d-inline-block text-secondary font-weight-normal" href="{% url 'nikki:password_change' %}">
        パスワード変更
      </a>
    </div>

    <div class="col-12 col-md-4 mb-3">
      <a class="d-inline-block text-secondary font-weight-normal" href="{% url 'nikki:delete_user' user.pk %}">
        退会希望の方はこちら
      </a>
    </div>
  </div>

  <div class="text-center">
    <a class="switch btn btn-lg text-white mt-1 mb-2" href="{% url 'nikki:create_article' user.pk %}">
      日記を書く
    </a>
  </div>

  <section class="mt-5 mb-4">
    <p class="text-center font-weight-bold text-secondary mb-2">今までに投稿した日記</p>
    <div class="row mx-auto">
      {% for article in articles_list %}
      <div class="col-6 col-md-4 col-lg-3">
        <p class="title my-2">
          <a href="{% url 'nikki:detail_article' article.id %}">{{ article.title|truncatechars_html:20 }}</a>
        </p>
      </div>
      {% endfor %}
    </div>
  </section>

</div>
{% endblock %}